version: '3.8'
services:
  erupe:
    build:
      context: Build/.
      dockerfile: Dockerfile
    container_name: Erupe
    depends_on:
      - db
    volumes:
      - ./Erupe:/Erupe
    environment:
      - ERUPE_HOST=127.0.0.1
    ports:
      - 53312
      - 53310
      - 54001-54008
    restart: unless-stopped

  db:
    image: postgres:15.1-alpine
    volumes:
     - erupe-db:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=${ERUPE_DB_USERNAME}
     - POSTGRES_PASSWORD=${ERUPE_DB_PASSWORD}
    ports:
     - 5432
    restart: unless-stopped

volumes:
  erupe-db:
